### ISSUE TITLE
OS proxy doesn't work

### ISSUE THREAD

**Issue by cosbgn** [unjs/unenv#279]
### Environment

cloudflare workers

### Reproduction

```
import { S3Client } from "@aws-sdk/client-s3";

const s3Client = new S3Client({
        region: "auto",
        endpoint: `https://${ACCOUNT_ID}.r2.cloudflarestorage.com`,
        credentials: { accessKeyId, secretAccessKey},
})
```

### Describe the bug

If you try to initialize the S3 sdk in cloudflare workers it fails with `Cannot convert object to primitive value`.

After investigating with the r2 team we reached this conclusion:

```
It appears that Nuxt is using unenv to smooth over differences in runtimes
And one of the things it does on build is replace imports from os with a proxy that doesn't appear to be working correctly
```

### Additional context

S3 expects varables to be string, unenv is not passing them as string

**Comment by cosbgn** [comment]
Reproduction:

https://github.com/cosbgn/s3-bug-nitro
https://s3-bug-nitro.pages.dev

**Comment by fayazara** [comment]
Getting this error on production too - `Cannot convert object to primitive value at new S3Client`.

Anybody found a workaround yet?

**Comment by pi0** [comment]
Thanks for nice reproduction dear @cosbgn 

`@aws-sdk/client-s3` is a Node.js library (at least with default export conditions, ideally they should have used `exports` with `cloudflare` condition ), because of this, when Nitro is building your app for Cloudflare pages target, had to use Node.js polyfills and os was not implemented for current v1.

We are collaborating with wrangler team to push unenv v2 with full coverage of Node.js and use it for all pages deployments by default.

In the meantime, i have backported `node:os` implementation from v2 to v1 (#282) in unenv [`v1.10.0` release](https://github.com/unjs/unenv/releases/tag/v1.10.0). 

You can upgrade by removing lockfile and doing a `<pm> install` command.


In case of similar issues with Nitro, please feel free to directly report them to [unjs/nitro](https://github.com/unjs/nitro) repository itself.

**Comment by fayazara** [comment]
Thanks @pi0, looks like a new error is popping up now.

Works fine locally and on node runtime, but not on CF pages/workers

```
POST 500 /api/demo/images/client-upload
Error generating client upload URL:,TypeError: t is not a function
[nuxt] [request error] [unhandled] [500],Failed to generate client upload URL for essentials/3c44b4dc22-captain.png
  at FileStorage.getClientUploadUrl (chunks/_/index4.mjs:1:738219)  
  at async Object.handler (chunks/routes/api/demo/images/client-upload.post.mjs:1:583)  
  at async Object.handler (chunks/routes/api/demo/index.patch.mjs:1:85471)  
  at async chunks/routes/api/demo/index.patch.mjs:1:88608  
  at async chunks/routes/api/demo/index.patch.mjs:1:129366
  ```
  
  ```
  POST 500 /api/demo/images
Error uploading file:,TypeError: t is not a function
[nuxt] [request error] [unhandled] [500],Failed to upload file to essentials/792370e5a0-chatwoot.png
  at FileStorage.upload (chunks/_/index4.mjs:1:737861)  
  at async Object.handler (chunks/routes/api/demo/index.post.mjs:1:635)  
  at async Object.handler (chunks/routes/api/demo/index.patch.mjs:1:85471)  
  at async chunks/routes/api/demo/index.patch.mjs:1:88608  
  at async chunks/routes/api/demo/index.patch.mjs:1:129366
  ```
  
  this is my S3 service
  
  ```ts
  import {
  S3Client,
  PutObjectCommand,
  DeleteObjectCommand,
  GetObjectCommand,
} from "@aws-sdk/client-s3";
import { getSignedUrl as getS3SignedUrl } from "@aws-sdk/s3-request-presigner";

let s3Client: S3Client | null = null;

const getS3Client = (): S3Client => {
  if (s3Client) return s3Client;

  const s3Endpoint = process.env.S3_ENDPOINT as string;
  const s3AccessKeyId = process.env.S3_ACCESS_KEY_ID as string;
  const s3SecretAccessKey = process.env.S3_SECRET_ACCESS_KEY as string;
  if (!s3Endpoint || !s3AccessKeyId || !s3SecretAccessKey) {
    throw new Error("Missing S3 configuration. Please check your environment variables.");
  }

  s3Client = new S3Client({
    region: "auto",
    endpoint: s3Endpoint,
    credentials: {
      accessKeyId: s3AccessKeyId,
      secretAccessKey: s3SecretAccessKey,
    },
  });

  return s3Client;
};

export class FileStorage {
  private s3Client: S3Client;
  private bucket: string;
  private s3PublicUrl: string;

  constructor() {
    this.bucket = process.env.S3_BUCKET_NAME ?? "";
    this.s3PublicUrl = process.env.S3_PUBLIC_ACCESS_URL ?? "";
    if (!this.bucket) {
      throw new Error("Missing S3_BUCKET_NAME. Please check your environment variables.");
    }

    this.s3Client = getS3Client();
  }

  async upload(key: string, data: Buffer | Blob | string): Promise<void> {
    let body: Buffer | string;
    if (data instanceof Blob) {
      body = Buffer.from(await data.arrayBuffer());
    } else {
      body = data;
    }

    const command = new PutObjectCommand({
      Bucket: this.bucket,
      Key: key,
      Body: body,
    });

    try {
      await this.s3Client.send(command);
    } catch (error) {
      console.error("Error uploading file:", error);
      throw new Error(`Failed to upload file to ${this.bucket}/${key}`);
    }
  }

  getObjectUrl(key: string): string {
    return `${this.s3PublicUrl}/${this.bucket}/${key}`;
  }

  async getClientUploadUrl(
    key: string,
    contentType: string,
    expiresIn: number = 3600,
  ): Promise<string> {
    try {
      return await getS3SignedUrl(
        this.s3Client,
        new PutObjectCommand({
          Bucket: this.bucket,
          Key: key,
          ContentType: contentType,
        }),
        { expiresIn },
      );
    } catch (error) {
      console.error("Error generating client upload URL:", error);
      throw new Error(`Failed to generate client upload URL for ${this.bucket}/${key}`);
    }
  }

  async delete(key: string): Promise<void> {
    const command = new DeleteObjectCommand({
      Bucket: this.bucket,
      Key: key,
    });

    try {
      await this.s3Client.send(command);
    } catch (error) {
      console.error("Error deleting file:", error);
      throw new Error(`Failed to delete file from ${this.bucket}/${key}`);
    }
  }

  async getSignedUrlForRead(key: string, expiresIn: number = 3600): Promise<string> {
    try {
      return await getS3SignedUrl(
        this.s3Client,
        new GetObjectCommand({ Bucket: this.bucket, Key: key }),
        { expiresIn },
      );
    } catch (error) {
      console.error("Error generating signed URL for read:", error);
      throw new Error(`Failed to generate signed URL for reading ${this.bucket}/${key}`);
    }
  }
}
```
  
 I will make a reproduction and create a issue on the nitro repo.
