### ISSUE TITLE
[error] [nitro] RollupError: .nuxt/dist/server/_nuxt/prompt-B4itIOXq.js (1:9): "stdin" is not exported

### ISSUE THREAD

**Issue by mrnasil** [unjs/unenv#315]
### Environment

![image](https://github.com/user-attachments/assets/65ad2fdf-2fda-4a5a-b280-659daee02833)

### Reproduction

Cloudflare Workers

### Describe the bug

Cloudflare Workers sometimes gives this error.

### Logs

```sh
17:32:29.912 [info] [nitro] Building Nuxt Nitro server (preset: `cloudflare-pages`)
17:32:42.265 [error] [nitro] RollupError: .nuxt/dist/server/_nuxt/prompt-B4itIOXq.js (1:9): "stdin" is not exported by "node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/node/process/index.mjs", imported by ".nuxt/dist/server/_nuxt/prompt-B4itIOXq.js".
17:32:42.266 
17:32:42.266 
17:32:42.266 1: import { stdin, stdout } from "node:process";
17:32:42.267             ^
17:32:42.267 2: import f from "node:readline";
17:32:42.267 3: import { WriteStream } from "node:tty";
17:32:42.268 [error] .nuxt/dist/server/_nuxt/prompt-B4itIOXq.js (1:9): "stdin" is not exported by "node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/node/process/index.mjs", imported by ".nuxt/dist/server/_nuxt/prompt-B4itIOXq.js".
17:32:42.269   at getRollupError (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/parseAst.js:395:41)
17:32:42.269   at error (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/parseAst.js:391:42)
17:32:42.269   at Module.error (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:15535:16)
17:32:42.269   at Module.traceVariable (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:15984:29)
17:32:42.269   at ModuleScope.findVariable (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:13770:39)
17:32:42.269   at ChildScope.findVariable (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:5252:38)
17:32:42.269   at ClassBodyScope.findVariable (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:5252:38)
17:32:42.269   at ChildScope.findVariable (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:5252:38)
17:32:42.269   at ChildScope.findVariable (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:5252:38)
17:32:42.270   at FunctionScope.findVariable (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:5252:38) 
17:32:42.270 
17:32:42.270 [error] .nuxt/dist/server/_nuxt/prompt-B4itIOXq.js (1:9): "stdin" is not exported by "node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/node/process/index.mjs", imported by ".nuxt/dist/server/_nuxt/prompt-B4itIOXq.js".
17:32:42.391 Failed: Error while executing user command. Exited with error code: 1
17:32:42.402 Failed: build command exited with code: 1
17:32:45.153 Failed: error occurred while running build command
```

**Comment by pi0** [comment]
unenv v1 does not have named mock exports for `stdin`/`stdout` but it is not a bug per-se.

If you could provide a minimal reproduction, please share it in nitro repo so i can help to investigate.

or feel free to share more context in our tweeter chat.

**Comment by mrnasil** [comment]
.npmrc:
shamefully-hoist=true
strict-peer-dependencies=false

This very interestingly solved our issue. If I access more information, I will definitely share an update. Thank you.

**Comment by pi0** [comment]
Thanks for sharing update. It is hositing issue then likely with wrangler dependency on unenv v2...
