### ISSUE TITLE
Incompatible with express.js

### ISSUE THREAD

**Issue by Tofandel** [unjs/unenv#328]
### Environment

Nuxt

### Reproduction

```js
import createApp from 'express';
import {IncomingMessage, ServerResponse as OriginalServerResponse} from "node:http";
import setPrototypeOf from 'setprototypeof';

// This is taken from the unenv implementation but minimized for reproducibility
class ServerResponse {
  __unenv__ = true;
  statusCode = 200;
  statusMessage = "";
  upgrading = false;
  chunkedEncoding = false;
  shouldKeepAlive = false;
  useChunkedEncodingByDefault = false;
  sendDate = false;
  finished = false;
  headersSent = false;
  strictContentLength = false;
  connection = null;
  socket = null;
  req;
  _headers = {};
  constructor(req) {
    this.req = req;
  }
  assignSocket(socket) {
    socket._httpMessage = this;
    this.socket = socket;
    this.connection = socket;
    this.emit("socket", socket);
    this._flush();
  }
  _flush() {
    this.flushHeaders();
  }
  detachSocket(_socket) {
  }
  writeContinue(_callback) {
  }
  writeHead(statusCode, arg1, arg2) {
    if (statusCode) {
      this.statusCode = statusCode;
    }
    if (typeof arg1 === "string") {
      this.statusMessage = arg1;
      arg1 = void 0;
    }
    const headers = arg2 || arg1;
    if (headers) {
      if (Array.isArray(headers)) ; else {
        for (const key in headers) {
          this.setHeader(key, headers[key]);
        }
      }
    }
    this.headersSent = true;
    return this;
  }
  writeProcessing() {
  }
  setTimeout(_msecs, _callback) {
    return this;
  }
  appendHeader(name, value) {
    name = name.toLowerCase();
    const current = this._headers[name];
    const all = [
      ...Array.isArray(current) ? current : [current],
      ...Array.isArray(value) ? value : [value]
    ].filter(Boolean);
    this._headers[name] = all.length > 1 ? all : all[0];
    return this;
  }
  setHeader(name, value) {
    this._headers[name.toLowerCase()] = value;
    return this;
  }
  getHeader(name) {
    return this._headers[name.toLowerCase()];
  }
  getHeaders() {
    return this._headers;
  }
  getHeaderNames() {
    return Object.keys(this._headers);
  }
  hasHeader(name) {
    return name.toLowerCase() in this._headers;
  }
  removeHeader(name) {
    delete this._headers[name.toLowerCase()];
  }
  addTrailers(_headers) {
  }
  flushHeaders() {
  }
  writeEarlyHints(_headers, cb) {
    if (typeof cb === "function") {
      cb();
    }
  }
}

const req = new IncomingMessage();
const res = new ServerResponse(req);

// This is taken from the express implementation
const app = createApp();
setPrototypeOf(res, app.response);

res.setHeader('vary', 'test'); // TypeError: Cannot set properties of undefined (setting 'vary')
```

### Describe the bug

When using unenv to send a request to an express server, a server error occurs

**Comment by Tofandel** [comment]
What would be the best way to solve this issue?
From the top of my head I could see a few solutions

1. We could export 2 differents `unenv/runtime/fetch/index` using the `package.json` exports field and specify one for node and one for default

2. We could have `IncomingMessage` and `ServerResponse` files function as polyfills and if importing `node:http` fails then we export the unenv implementation, otherwise we export the node implementation

3. We could import from `node:http` from the fetch implementation and let the rollup aliasing do the job

**Comment by pi0** [comment]
Using this minimal reproduction to followup:

```js
import express from 'express';
import { createFetch, createCall } from "unenv/runtime/fetch/index"; // unenv@1.10.0
const app = express({ debug: true }).use('/test', (req, res) => {
  try {
      res.setHeader('vary', 'test');
    res.send('Hello World')
  } catch (err) {
    console.error(err)
    throw err
  }
})
const serverFetch = createFetch(createCall(app));
const res = await serverFetch("/test", { headers: { foo: "bar" } });
console.log({
  headers: res.headers.entries(),
  body: await res.text()
})
```

```
TypeError: Cannot convert undefined or null to object
    at ServerResponse.removeHeader (node:_http_outgoing:799:30)
    at write (/Users/pooya/tmp/unenv-playground/node_modules/.pnpm/finalhandler@1.3.1/node_modules/finalhandler/index.js:287:9)
    at send (/Users/pooya/tmp/unenv-playground/node_modules/.pnpm/finalhandler@1.3.1/node_modules/finalhandler/index.js:311:5)
    at Immediate.<anonymous> (/Users/pooya/tmp/unenv-playground/node_modules/.pnpm/finalhandler@1.3.1/node_modules/finalhandler/index.js:135:5)
    at Immediate.<anonymous> (/Users/pooya/tmp/unenv-playground/node_modules/.pnpm/express@4.21.1/node_modules/express/lib/router/index.js:646:15)
    at process.processImmediate (node:internal/timers:478:21)
```

---

Ideally, express should use the runtime `IncomingMessage` / `ServerResponse` prototypes (which in case of direct fetch in nitro, is polyfill). (I noticed you made https://github.com/expressjs/express/issues/6039 upstream issue thanks 🙏🏼 )

Alternatively we could make unenv polyfill compat by exposing `[kOutHeaders]` prop (issue is that Symbol is node internal!)

**Comment by Tofandel** [comment]
I was thinking that the best way would be that in the node preset, we just alias `unenv/runtime/node/http/_request` to the native node request and make sure the createCall implementation works with the native module

Why use the polyfill when have the natives available?

> Ideally, express should use the runtime IncomingMessage / ServerResponse

The problem is they are doing some weird thing instantiating request and response before runtime fetch, so you can add your own methods to them. Their approach is bad practice all over really. I opened https://github.com/expressjs/express/pull/6047 which would fix this by stopping the prototype inheritance to only the methods added to the express req and res

**Comment by pi0** [comment]
Node.js native `IncomingMessage` is not intended for usage of `unenv/fetch` utility.

We are emulating an HTTP request without actually making a network round trip (otherwise you need to listen an express server and fetch with absolute URL. relative URL fetch is also not supported by node on server). `IncomingMessage` constructor expects an actual Socket and `ServerResponse` also to be streamed back.

**Comment by Tofandel** [comment]
I guess this could be addressed by having a different polyfill for node, where we just override what we need to make it work and alias to that instead in the preset

Something like
```js
export class IncomingMessage extends http.IncomingMessage { // Extend the native implementation
  // Override some stuff
}
```

Where `// Override some stuff` is pretty much whats already in the original polyfill

**Comment by Tofandel** [comment]
> it is not a polyfill

Right, it's an emulation, but at the end of the local request, it is expected to be a server running on the env set by the preset, so if it normally works on the native http implementation, it's expected to have the exact same behavior on the direct call, and having a mix of sometimes the native implementation and sometimes the polyfill depending on direct request or not leads to those edge cases

I guess this could be addressed by having a different polyfill for node, where we just override what we need to make it work and alias to that instead in the preset

Something like
```js
export class IncomingMessage extends http.IncomingMessage { // Extend the native implementation
  // Override some stuff
}
```

I can see a way to avoid the duplicated code by having in the original

```js
export class ServerResponse extends NodeServerResponseOrWritable
```

Where NodeServerResponseOrWritable will resolve to either `Writable` or the `http.IncomingMessage` with a proxy file and aliasing

Otherwise the parameters you mention are not required and `const res = new http.IncomingMessage(); const req = new http.Request(res)` do work on their own and methods don't seem to error, so with some events on the http.Request we could emulate it properly

`node -e "import {IncomingMessage, ServerResponse} from 'node:http'; console.log(new ServerResponse(new IncomingMessage()).write('test'))"`

**Comment by pi0** [comment]
> it is expected to be a server running on the env set by the preset

No actually the util does not depends on a running server that's the whole point/benefit. 


> I guess this could be addressed by having a different polyfill for node, where we just override what we need to make it work and alias to that instead in the preset

While o agree that it could be one possible solution to extend `nodeHTTP.IncomingMessage` I'm inclined to avoid doing this (mixing with built-in) as much as possible as it makes unenv behavior dependent on runtime internals by extending their built-in classes.

We have Node.js, Workerd, Bun and Deno with at least 4 different (internal) implementations of `http.IncomingMessage` then to care of and I'm afraid it is not just matter of extending. 

The root cause of express incompatibility is actually a wrong mix that express tries to call `http.IncomingMessage.removeHeader` on an incompatible class (and your PR upstream is fixing it), by extending, actually we increase the similar chances.

It probably makes sense for `node:stream` to be extended from runtime's built-in (#365) because built-in node streams could be compatible but not for `node:http` and solves #332.

**Comment by pi0** [comment]
With all this said, if you still like to invest time on making a `node:http` mocking solution with extending node built-in `IncomingMessage`/`ServerResponse`, I would love to see a draft PR and evaluate, not strictly against it.

But it will be a long path and we need someone to constantly maintain it ensuring will be compatible with future runtime changes.

This time could be spent on better places such as stream support (#365) I can invite you to [another](https://www.npmjs.com/package/nstdlib-nightly) effort we are trying to make sure unenv impl is **same** as Node.js for critical modules as as `node:streams`)
