### ISSUE TITLE
Issue with libraries importing from `buffer/`

### ISSUE THREAD

**Issue by williamchong** [unjs/unenv#371]
### Environment

Nuxt 3.14 with `clientNodeCompat: true`

### Reproduction

https://codesandbox.io/p/devbox/gifted-lamarr-clm2ng?workspaceId=ws_FkMsQvKkgFLx4xGAjKdYES

### Describe the bug

Many libraries still follow the practice of using
```javascript
import { Buffer } from 'buffer/';
```
to force `buffer` to be the npm package version instead of the built-in one.  (note the tailing slash)

`uenv` seems to treat that tailing slash as an actual path, resolving it as `unenv/runtime/node/buffer/index/` which cannot be found

Please advice if this is an `unenv` or a `nuxt` issue

### Additional context

Also found in https://github.com/nuxt/nuxt/discussions/29978

### Logs

```sh
Error: Build failed with 3 errors:
node_modules/@keystonehq/bc-ur-registry/dist/index.js:6:25: ERROR: Could not read from file: /project/workspace/unenv/runtime/node/buffer/index
node_modules/@toruslabs/openlogin-jrpc/node_modules/readable-stream/lib/_stream_readable.js:158:48: ERROR: Could not read from file: /project/workspace/unenv/runtime/node/string_decoder/index
node_modules/readable-stream/lib/internal/streams/end-of-stream.js:3:24: ERROR: Could not read from file: /project/workspace/unenv/runtime/node/process/index
    at failureErrorWithLog (/project/workspace/node_modules/vite/node_modules/esbuild/lib/main.js:1472:15)
    at /project/workspace/node_modules/vite/node_modules/esbuild/lib/main.js:945:25
    at /project/workspace/node_modules/vite/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by williamchong** [comment]
Maybe also related https://github.com/unjs/unenv/issues/39#issuecomment-2479645189

**Comment by pi0** [comment]
this is not a direct issue with unenv. Libraries use `buffer/` trick to actually intentionally **escape** and force using [`npm/buffer`](https://www.npmjs.com/package/buffer) sadly.

**Comment by williamchong** [comment]
Then unenv should not touch these entries by default? 
i.e. don’t turn them into unenv/runtime/node/buffer/index/

**Comment by pi0** [comment]
This is a quirk that should be handled on bundler-level configuration (Nuxt and Nitro)

I did an attempt on #436 however esbuild for example does not even allow `buffer/` as an alias!
